### ISSUE TITLE
SamplerCustomAdvanced  forward_orig() got an unexpected keyword argument 'attn_mask'

### ISSUE THREAD

**Issue by neom315** [sipie800/ComfyUI-PuLID-Flux-Enhanced#55]
as the title says.
Since updating to 0.39 seems like PuLID return this error every time the sampler start, writing on the git of comfyui they say it's a custom node issue.

Any help apreciated 

p.s.
i have updated all the custom nodes as comfyui itself

**Comment by adamreading** [comment]
same

**Comment by Skallagrimr** [comment]
same issue, any solution?

**Comment by adamreading** [comment]
> same issue, any solution?

Yup, my friend forked and fixed it. https://github.com/XmYx/ComfyUI-PuLID-Flux-Enhanced/

**Comment by neom315** [comment]
> > same issue, any solution?
> 
> Yup, my friend forked and fixed it. https://github.com/XmYx/ComfyUI-PuLID-Flux-Enhanced/

i have replaced the pulidflux.py script with the one provided, but the error persist, no solution found so far

**Comment by adamreading** [comment]
> > > same issue, any solution?
> > 
> > 
> > Yup, my friend forked and fixed it. https://github.com/XmYx/ComfyUI-PuLID-Flux-Enhanced/
> 
> i have replaced the pulidflux.py script with the one provided, but the error persist, no solution found so far

I had to remove the node and reinstall it from the fork and it worked perfectly after that

**Comment by neom315** [comment]
> > > > same issue, any solution?
> > > 
> > > 
> > > Yup, my friend forked and fixed it. https://github.com/XmYx/ComfyUI-PuLID-Flux-Enhanced/
> > 
> > 
> > i have replaced the pulidflux.py script with the one provided, but the error persist, no solution found so far
> 
> I had to remove the node and reinstall it from the fork and it worked perfectly after that

i have deleted the folder as suggested and place the node after downloading it from the location, but i still receive the same error, do you need to install again some elements from the requirements.txt or install from cmd?

**Comment by harelc** [comment]
We just need #51 to be merged, that solves it - I can confirm. No manual code patching..

**Comment by harelc** [comment]
@sipie800 any chance you can merge #51 ? see above. Currently this repo is broken for recent Comfy. #51 fixes it.

**Comment by ak3389** [comment]
> > 同样的问题，有解决办法吗？
> 
> 是的，我的朋友分叉并修复了它。https [://github.com/XmYx/ComfyUI-PuLID-Flux-Enhanced/](https://github.com/XmYx/ComfyUI-PuLID-Flux-Enhanced/)

Desktop version cannot be installed via git

**Comment by neom315** [comment]
Still no universal solution to fix the issue?

**Comment by vahidzxc** [comment]
any solution?

**Comment by kubilaykilinc** [comment]
> any solution?
https://github.com/sipie800/ComfyUI-PuLID-Flux-Enhanced/issues/54#issuecomment-2564375619

**Comment by neom315** [comment]
> > any solution?
> > [#54 (comment)](https://github.com/sipie800/ComfyUI-PuLID-Flux-Enhanced/issues/54#issuecomment-2564375619)

Nothing so far i have tried everything, all single solution that are indexed here for me don't work.

**Comment by harelc** [comment]
The fix is #51, we just need to merge it here. Or you can git checkout that branch from the forked repo to fix it until repo owner merges it.

**Comment by neom315** [comment]
> The fix is #51, we just need to merge it here. Or you can git checkout that branch from the forked repo to fix it until repo owner merges it.

i am sorry to sound dumb, but i have no idea how to do that

**Comment by neom315** [comment]
i tried as well the proposed modification on the model.py, but after doing so a new error pop up

forward_orig() takes from 7 to 9 positional arguments but 10 were given

**Comment by kubilaykilinc** [comment]
This is solution. It's working for me. 

https://github.com/sipie800/ComfyUI-PuLID-Flux-Enhanced/issues/54#issuecomment-2564375619

**Comment by neom315** [comment]
> This is solution. It's working for me.
> 
> [#54 (comment)](https://github.com/sipie800/ComfyUI-PuLID-Flux-Enhanced/issues/54#issuecomment-2564375619)

This solution works for a different type of error, it's calling for 

Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking argument for argument weight in method wrapper_CUDA__native_layer_norm)

but now my error is

forward_orig() takes from 7 to 9 positional arguments but 10 were given

**Comment by kubilaykilinc** [comment]
Are you using comfyui pulid flux enhanced? Or Comfyui Pulid Flux custom node.
Which one?

**Comment by neom315** [comment]
> Are you using comfyui pulid flux enhanced? Or Comfyui Pulid Flux custom node. Which one?

i am using the ComfyUI-PuLID-Flux-Enhanced

**Comment by kubilaykilinc** [comment]
> > Are you using comfyui pulid flux enhanced? Or Comfyui Pulid Flux custom node. Which one?
> 
> i am using the ComfyUI-PuLID-Flux-Enhanced

https://github.com/cubiq/PuLID_ComfyUI/issues/109#issuecomment-2506898447

**Comment by neom315** [comment]
> > > Are you using comfyui pulid flux enhanced? Or Comfyui Pulid Flux custom node. Which one?
> > 
> > 
> > i am using the ComfyUI-PuLID-Flux-Enhanced
> 
> [cubiq/PuLID_ComfyUI#109 (comment)](https://github.com/cubiq/PuLID_ComfyUI/issues/109#issuecomment-2506898447)

this modification is the one that cause me the error in the first place, before changing the line in the model.py i had the one i posted in my original post

**Comment by neom315** [comment]
> 1- Update your comfyui 2- Uninstall Comfyui Pulid Flux Enhanced 3- Reinstall again this custom node 4- Update this manually [#54 (comment)](https://github.com/sipie800/ComfyUI-PuLID-Flux-Enhanced/issues/54#issuecomment-2564375619) 5- Remove old pulid nodes on your workflow. Create new nodes.
> 
> If it doesn't work - i have not another solution sorry

1 done
2 done
3 what custom node? the flux enchance again? because i have installed 2 different ones and they didn't work
4 done
5 done

now with this setup i get this error 

expected scalar type Half but found BFloat16

**Comment by kubilaykilinc** [comment]
> > 1- Update your comfyui 2- Uninstall Comfyui Pulid Flux Enhanced 3- Reinstall again this custom node 4- Update this manually [#54 (comment)](https://github.com/sipie800/ComfyUI-PuLID-Flux-Enhanced/issues/54#issuecomment-2564375619) 5- Remove old pulid nodes on your workflow. Create new nodes.
> > If it doesn't work - i have not another solution sorry
> 
> 1 done 2 done 3 what custom node? the flux enchance again? because i have installed 2 different ones and they didn't work 4 done 5 done
> 
> now with this setup i get this error
> 
> expected scalar type Half but found BFloat16

We have some options:
1- You can install fresh new last version comfyui and install this custom node and fix manually
2- If you want your actual installed comfyui, maybe your workflow has conflict things.

**Comment by neom315** [comment]
Apparently this is the situation with the error i am reporting, until the pulid node will not be updated there will be still people with the same error

https://github.com/comfyanonymous/ComfyUI/issues/6077#issuecomment-2566764175

**Comment by hzeasy** [comment]
> > 同样的问题，有解决办法吗？
> 
> 是的，我的朋友分叉并修复了它。https [://github.com/XmYx/ComfyUI-PuLID-Flux-Enhanced/](https://github.com/XmYx/ComfyUI-PuLID-Flux-Enhanced/)

This method works! Replace this fork and it will be normal, thanks.

**Comment by neom315** [comment]
> > > 同样的问题，有解决办法吗？
> > 
> > 
> > 是的，我的朋友分叉并修复了它。https [://github.com/XmYx/ComfyUI-PuLID-Flux-Enhanced/](https://github.com/XmYx/ComfyUI-PuLID-Flux-Enhanced/)
> 
> This method works! Replace this fork and it will be normal, thanks.

not for me, this method is not fixing the error at all

**Comment by Woukim** [comment]
> not for me, this method is not fixing the error at all
> and if you check the python script is the same as it was 2 weeks ago with all other file in the node to be 3 months old

Hi, I just updated the ComfyUI after replacing pulidflux and it worked!
